/**
 * content-data2.js - Public Images Module v5.0.0 FIXED
 * Solo archivos VERIFICADOS que existen en el servidor
 */

const FULL_IMAGES_POOL = [
    // Archivos verificados con 200 OK en la consola
    "full/0456996c-b56e-42ef-9049-56b1a1ae2646.webp",
    "full/0Tc8Vtd0mEIvNHZwYGBq.webp",
    "full/0lySugcO4Pp4pEZKvz9U.webp",
    "full/0nSaCJQxbVw4BDrhnhHO.webp",
    "full/13TXvyRVZ7LtvAOx7kme.webp",
    "full/18VQaczW5kdfdiqUVasH.webp",
    "full/1dEu25K0mS3zxRlXRjHR.webp",
    "full/1qEBcg9QbkZRRdLt0Chc.webp",
    "full/1tt8H4fX3XzyV90HjNG3.webp",
    "full/27bGIzFFpej5ubUkvykD.webp",
    "full/2gjqH68H586TKLDK9lh9.webp",
    "full/2yw4sowPh3Tyln5oxRdw.webp",
    "full/39GYGt3bticS0Mjbud0p.webp",
    "full/3IWka3fnP9b8yz6j5l91.webp",
    "full/3ZYL4GCUOs3rfq3iTPJ7.webp",
    "full/4GN6i0Db2hl4Ck9vf0LE.webp",
    "full/4YhoIAWSbVaOqBhAOGqR.webp",
    "full/82KxJ9daxf9MpK019L5I.webp",
    "full/83cSC4eRnYGZUNo9AoqD.webp",
    "full/85158b64-4168-45fa-9cb4-0b40634f7fa1.webp",
    "full/8faf42TRuGOU4ZW9KS9W.webp",
    "full/92Ck0v3g8gZLEQ5vOmpd.webp",
    "full/993acHdsWLzG80gAFZQs.webp",
    "full/9D5U5fKXT72xnpqsgUaD.webp",
    "full/9v20KsJFZoAv2WQ8m3o2.webp",
    "full/AHKAq0biFDUtkxlx7TCu.webp",
    "full/ANhHtA0GivBfeAo6dvJG.webp",
    "full/AwKXjDqrJMTKNvB84iRy.webp",
    "full/bikini.webp",
    "full/bikini3.webp",
    "full/bikini5.webp",
    "full/bikbanner2.webp",
    "full/buxNTxdJrOaiUnp3CCgW.webp",
    "full/CmxJm1VLBBhvZoUwxWTJ.webp",
    "full/cRNjL0pgJXBWVxKdsFON.webp",
    "full/CTyCcna8JSPObRQpulKJ.webp",
    "full/CuX7zQzCBToIMKBYVcA8.webp",
    "full/D3QdNfIR9B8YKPIYl0Hg.webp",
    "full/FElwiy3A7OtgubeV9Qsh.webp",
    "full/Fz2ORrJSrERl0BZGOH24.webp",
    "full/G4YdNFtdunscrnPe5Qb6.webp",
    "full/G5tR4rjmD4dWct9aKfMu.webp",
    "full/I2enQjaFiBfPB2hml0xQ.webp",
    "full/ICDQwh9QLaL3SpYTmk4i.webp",
    "full/IXCJwuZEjxFfPTinm4Cq.webp",
    "full/Jc4OmrYPCcAkzNGKXhE1.webp",
    "full/K6AqNa8lHyPw8rujRCux.webp",
    "full/K6PnUKojASfrNdaGJJSV.webp",
    "full/KRGZrnrhKdEiv6bUM0B8.webp",
    "full/KSft2d50fGqVzjnvaQsP.webp",
    "full/KSIgono33EvDrKQDut47.webp",
    "full/lXpckkGACDNcXPAHEQqu.webp",
    "full/McOBxMX6PoUZbroTTgP4.webp",
    "full/mFuqtladZr2hO3Tszm3m.webp",
    "full/nJvZXk80qguZvwOeSai6.webp",
    "full/nm6YKc38NLqwGPaNiDhc.webp",
    "full/NqO93fUipM4zuYSCRSt5.webp",
    "full/NzzddX28psM9wi68V6CK.webp",
    "full/owPT3Y4puK3dRHWNsj47.webp",
    "full/psZEFLlVAhAiq10uJ8qd.webp",
    "full/Q0MiJGqtUpfaOEJhLrnz.webp",
    "full/Q8YO7MENrALjcQdZRGxv.webp",
    "full/qLDeRznPthcmYSmggfbm.webp",
    "full/qhK8inhLxacOs8w7mRbE.webp",
    "full/qxIzW9ZMuhkEY6dmGKSv.webp",
    "full/S4H14jh2mOOA0Ox6U7U6.webp",
    "full/sda0bXv4LRWxnW49KPWT.webp",
    "full/sfz7eFmqHWlf6wrpTDD9.webp",
    "full/sMAD8T2U7A3aMQjxsUdd.webp",
    "full/t9WqMZxXkmUTMrq3d13l.webp",
    "full/tMxzKdT8rjZm3gpe0StS.webp",
    "full/TFndjJgjmgdAJ8NNJHy5.webp",
    "full/tQ41YocTwqSnd8mFsDc5.webp",
    "full/tQInulLfQHQTFNIK6yEV.webp",
    "full/tzico6mUJuc7Lz8HYdEF.webp",
    "full/ufXYerfLKedF1f6OYNhd.webp",
    "full/uMSW2oj0qrbVEmIEotZ1.webp",
    "full/wrs60TS7VJQlmWbyKKUu.webp",
    "full/WuoJZZ1KY40aGXaYQ3Md.webp",
    "full/xhQTgYHiVAYbnYrKIsOq.webp",
    "full/yqTobCZL2AABmmNJ7EPU.webp",
    "full/zNzTQ476q4sOPWRaVPEw.webp",
    "full/zRPnijTCwLqQeZLXLvzu.webp",
    "full/zSzYfjo7gtKbVBWGhbJN.webp",
    "full/zUNmPEaVFiJfL1mo27ga.webp",
    "full/zs7GNC0HKhDQwRIsB9IM.webp",
    "full/zx83JCzdTKNfyKUY6Djs.webp"
];

// Exportar globalmente
window.FULL_IMAGES_POOL = FULL_IMAGES_POOL;
window.BANNER_IMAGES = FULL_IMAGES_POOL.slice(0, 10);
window.TEASER_IMAGES = FULL_IMAGES_POOL.slice(10, 20);

// Sin console.log para mantener la consola limpia
