/**
 * content-data2.js - Public Images Module v4.1.0 UPDATED
 * Contains all public/full images (127 files) - COMPLETE LIST
 */

console.log("📦 Cargando módulo content-data2.js - Imágenes públicas (127 archivos)...");

const FULL_IMAGES_POOL = [
    "full/0456996c-b56e-42ef-9049-56b1a1ae2646.webp",
    "full/0Tc8Vtd0mEIvNHZwYGBq.webp",
    "full/0lySugcO4Pp4pEZKvz9U.webp",
    "full/0nSaCJQxbVw4BDrhnhHO.webp",
    "full/13TXvyRVZ7LtvAOx7kme.webp",
    "full/18VQaczW5kdfdiqUVasH.webp",
    "full/1dEu25K0mS3zxRlXRjHR.webp",
    "full/1qEBcg9QbkZRRdLt0Chc.webp",
    "full/1tt8H4fX3XzyV90HjNG3.webp",
    "full/27bGIzFFpej5ubUkvykD.webp",
    "full/2gjqH68H586TKLDK9lh9.webp",
    "full/2yw4sowPh3Tyln5oxRdw.webp",
    "full/39GYGt3bticS0Mjbud0p.webp",
    "full/3IWka3fnP9b8yz6j5l91.webp",
    "full/3ZYL4GCUOs3rfq3iTPJ7.webp",
    "full/4GN6i0Db2hl4Ck9vf0LE.webp",
    "full/4YhoIAWSbVaOqBhAOGqR.webp",
    "full/82KxJ9daxf9MpK019L5I.webp",
    "full/83cSC4eRnYGZUNo9AoqD.webp",
    "full/85158b64-4168-45fa-9cb4-0b40634f7fa1.webp",
    "full/8faf42TRuGOU4ZW9KS9W.webp",
    "full/92Ck0v3g8gZLEQ5vOmpd.webp",
    "full/993acHdsWLzG80gAFZQs.webp",
    "full/9D5U5fKXT72xnpqsgUaD.webp",
    "full/9v20KsJFZoAv2WQ8m3o2.webp",
    "full/AHKAq0biFDUtkxlx7TCu.webp",
    "full/ANhHtA0GivBfeAo6dvJG.webp",
    "full/AwKXjDqrJMTKNvB84iRy.webp",
    "full/CTyCcna8JSPObRQpulKJ.webp",
    "full/CmxJm1VLBBhvZoUwxWTJ.webp",
    "full/CuX7zQzCBToIMKBYVcA8.webp",
    "full/D3QdNfIR9B8YKPIYl0Hg.webp",
    "full/FElwiy3A7OtgubeV9Qsh.webp",
    "full/Fz2ORrJSrERl0BZGOH24.webp",
    "full/G4YdNFtdunscrnPe5Qb6.webp",
    "full/G5tR4rjmD4dWct9aKfMu.webp",
    "full/I2enQjaFiBfPB2hml0xQ.webp",
    "full/ICDQwh9QLaL3SpYTmk4i.webp",
    "full/IXCJwuZEjxFfPTinm4Cq.webp",
    "full/Jc4OmrYPCcAkzNGKXhE1.webp",
    "full/K6PnUKojASfrNdaGJJSV.webp",
    "full/KAmyoR6DGyMRCn0RJnJG.webp",
    "full/LGhxf7qSczqJfrCRWSQT.webp",
    "full/LYn11zY3o2o5Iuxr1Nfm.webp",
    "full/MMAWnVfWnXoLwqkxKxCh.webp",
    "full/MWKCVnJRdv3cHLMfPT0z.webp",
    "full/NxU8VzTLqcFjgkASUQhG.webp",
    "full/O3xdP0hCHHIdNNIi1AEt.webp",
    "full/OIEwvSHCvRLN0mIqHkhn.webp",
    "full/Oh5Cv1G6WP3y9YYUUDXG.webp",
    "full/PF03fnudO7JMKzNcLhtH.webp",
    "full/Q0MiJGqtUpfaOEJhLrnz.webp",
    "full/Q8YO7MENrALjcQdZRGxv.webp",
    "full/Qg8hnzCTh5kIuKT2kxOF.webp",
    "full/R5PQIelLbLN7SJ8AHT9o.webp",
    "full/RCEbXvEH0dJJQFD7YEh0.webp",
    "full/RJ9fXQpGOhzxOhJ1p9uB.webp",
    "full/Rvj2QL6tYXTkbBBZP2aZ.webp",
    "full/S4H14jh2mOOA0Ox6U7U6.webp",
    "full/T8a8WzRy8o5EaEGOIQBY.webp",
    "full/TFndjJgjmgdAJ8NNJHy5.webp",
    "full/TKJvjD6SxX5W3zXazm3F.webp",
    "full/U5K5wYnN5AH2pQy5gu4u.webp",
    "full/UOmqQrnQbUIGvgHD1fuz.webp",
    "full/V1b8yUb9KwTTZxffrqUP.webp",
    "full/VF24GQk7zNy6mfgCnKDK.webp",
    "full/VRa7qEDm6QLNYsRHJhyB.webp",
    "full/Vw8OwdKyZw12tUCXQTl4.webp",
    "full/WQZBksO0ZHekEihBM4a1.webp",
    "full/XJO5jO9q7xaXRIXN5bfZ.webp",
    "full/YMShJ9l0qQUfzqn9TSnr.webp",
    "full/Yp8YV7H5DmHXRGXv9VcU.webp",
    "full/Z5OfPbyHYUFdcfkm1gGv.webp",
    "full/ZVQOsLBJuxJoI8GqZtfX.webp",
    "full/a0hGANQJVxTRRtHbfBCh.webp",
    "full/a96aWXepbw43a5WS2xA7.webp",
    "full/aOOojqpRcZBvX0Ycg2D8.webp",
    "full/aeiU4XNBLjgjzSgaqTD4.webp",
    "full/aepR9awBLznYhIoJEFQE.webp",
    "full/af5a652e-e94f-4d53-b34a-5bb25e7f78ce.webp",
    "full/bQG7q8jKZodbvUmqxo0V.webp",
    "full/cABOOqEhc7PeqcUYiJVj.webp",
    "full/cDlC1SYiJIcXkOmABCBF.webp",
    "full/cSxdJkQpOdQiCNtAiClZ.webp",
    "full/d23fac19-f2e3-4767-8663-df1e8cc96e7f.webp",
    "full/dZ9J4vczqS7LCdFJLIdG.webp",
    "full/ecfhLTWCqx9IQ5nkRCze.webp",
    "full/ekEfPiRzfBJKBN3Cd6TE.webp",
    "full/f22RKEpjeJdKOdNy7Ogw.webp",
    "full/fOkdSXP10aNzs7iTQkiF.webp",
    "full/fe7a3b5e-19d1-447f-a3f3-16e2f090beec.webp",
    "full/g3RFu8yQRJw1aXrROXzg.webp",
    "full/gxL9wXMWY6qRJJLAuSJJ.webp",
    "full/h8bGXLKCBw6SH8Y01nQL.webp",
    "full/hc2Nh5vBdUvUYt9kczEP.webp",
    "full/iIdg5G6Dd7vXzLy2uLwH.webp",
    "full/jIcLZTpAQWe6dfKiyoAN.webp",
    "full/jJaZUgqOEgXYWCFljYz3.webp",
    "full/jTSyAJInaPJl7z7HJD4a.webp",
    "full/kSifqxFJOiBwilLR65bV.webp",
    "full/kZcyiAnC5K1YAXKulB2e.webp",
    "full/kr5FiUdTaiQ7imq1xHlH.webp",
    "full/lXpckkGACDNcXPAHEQqu.webp",
    "full/mFuqtladZr2hO3Tszm3m.webp",
    "full/nJvZXk80qguZvwOeSai6.webp",
    "full/nm6YKc38NLqwGPaNiDhc.webp",
    "full/owPT3Y4puK3dRHWNsj47.webp",
    "full/psZEFLlVAhAiq10uJ8qd.webp",
    "full/qLDeRznPthcmYSmggfbm.webp",
    "full/qhK8inhLxacOs8w7mRbE.webp",
    "full/qxIzW9ZMuhkEY6dmGKSv.webp",
    "full/sMAD8T2U7A3aMQjxsUdd.webp",
    "full/sda0bXv4LRWxnW49KPWT.webp",
    "full/sfz7eFmqHWlf6wrpTDD9.webp",
    "full/t9WqMZxXkmUTMrq3d13l.webp",
    "full/tMxzKdT8rjZm3gpe0StS.webp",
    "full/tQ41YocTwqSnd8mFsDc5.webp",
    "full/tQInulLfQHQTFNIK6yEV.webp",
    "full/tzico6mUJuc7Lz8HYdEF.webp",
    "full/uMSW2oj0qrbVEmIEotZ1.webp",
    "full/ufXYerfLKedF1f6OYNhd.webp",
    "full/wrs60TS7VJQlmWbyKKUu.webp",
    "full/xhQTgYHiVAYbnYrKIsOq.webp",
    "full/yqTobCZL2AABmmNJ7EPU.webp",
    "full/zNzTQ476q4sOPWRaVPEw.webp",
    "full/zRPnijTCwLqQeZLXLvzu.webp",
    "full/zSzYfjo7gtKbVBWGhbJN.webp",
    "full/zUNmPEaVFiJfL1mo27ga.webp",
    "full/zs7GNC0HKhDQwRIsB9IM.webp",
    "full/zx83JCzdTKNfyKUY6Djs.webp"
];

console.log("✅ 127 imágenes públicas cargadas desde /full/");

// Exportar globalmente
window.FULL_IMAGES_POOL = FULL_IMAGES_POOL;

// Crear arrays de banners y teasers simples
window.BANNER_IMAGES = FULL_IMAGES_POOL.slice(0, 10);
window.TEASER_IMAGES = FULL_IMAGES_POOL.slice(10, 20);

console.log('✅ Módulo content-data2.js cargado correctamente - 127 ARCHIVOS COMPLETOS');
console.log('📊 Estadísticas de contenido público:', {
    total: FULL_IMAGES_POOL.length,
    banners: window.BANNER_IMAGES.length,
    teasers: window.TEASER_IMAGES.length
});
