#!/bin/bash
echo "============================================"
echo "VERIFICACIÓN DE INSTALACIÓN"
echo "============================================"
echo ""
echo "✅ Archivos creados:"
echo "-------------------"
ls -la service-worker.js 2>/dev/null && echo "✓ Service Worker actualizado"
ls -la js/ads-manager.js 2>/dev/null && echo "✓ Gestor de anuncios creado"
ls -la clear-cache.html 2>/dev/null && echo "✓ Página de limpieza de caché"
echo ""
echo "📝 Service Worker (primeras líneas):"
echo "------------------------------------"
head -n 3 service-worker.js 2>/dev/null
echo ""
echo "🌐 URLs importantes:"
echo "-------------------"
echo "Limpiar caché: https://tudominio.com/clear-cache.html"
echo "Página principal: https://tudominio.com/"
echo ""
echo "✅ Para completar la instalación:"
echo "1. Abre /clear-cache.html en tu navegador"
echo "2. Espera 2 segundos"
echo "3. Se recargará automáticamente"
echo "4. Verifica en F12 > Console que no hay errores"
echo "5. Los anuncios deberían aparecer en laterales y banners"
echo "============================================"
